name: jotflow
description: "A simple and easy to use notetaking app for your mobile device."
publish_to: 'none'
version: 0.1.1+4

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.8
  flutter_staggered_grid_view: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

flutter_native_splash:
  web: false
  color: "#ffffff"
  image: "assets/splash_icon.png"

  android_12:
    color: "#ffffff"
    image: "assets/splash_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/no_notes.png
  fonts:
    - family: "Poppins"
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800  
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

